src/Entity/Carrier.php
<?php

namespace App\Entity;

use App\Repository\CarrierRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarrierRepository::class)]
class Carrier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?float $price = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function __toString()
    {
        return $this->getName().'[br]'.$this->getDescription().'[br]'.number_format($this->getPrice(), 2, ',', ',').' €';
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $carrierName = null;

    #[ORM\Column]
    private ?float $carrierPrice = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $delivery = null;

    #[ORM\OneToMany(mappedBy: 'myOrder', targetEntity: OrderDetails::class)]
    private Collection $orderDetails;

    #[ORM\Column]
    private ?bool $isPaid = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $stripeSessionId = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getTotal()
    {
        $total = null;

        foreach ( $this->getOrderDetails()->getValues() as $product) {
            $total = $total + ($product->getPrice() * $product->getQuantity());
        }

        return $total;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): self
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(float $carrierPrice): self
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetails>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetails $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetails $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getMyOrder() === $this) {
                $orderDetail->setMyOrder(null);
            }
        }

        return $this;
    }

    public function isIsPaid(): ?bool
    {
        return $this->isPaid;
    }

    public function setIsPaid(bool $isPaid): self
    {
        $this->isPaid = $isPaid;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripeSessionId;
    }

    public function setStripeSessionId(?string $stripeSessionId): self
    {
        $this->stripeSessionId = $stripeSessionId;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Address;
use App\Entity\Carrier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
      $user = $options['user'];

        $builder
        //Entity class désign qu'il devra aller cherche les adresse dans les entité déjà existante
            ->add('addresses', EntityType::class, [
                'label' => false,
                'required' => true,
                'class' => Address::class,
                'choices' => $user->getAddresses(),
                'multiple' => false,
                'expanded' => true
            ])
            ->add('carriers', EntityType::class, [
                'label' => 'Choisissez votre transporteur',
                'required' => true,
                'class' => Carrier::class,
                'multiple' => false,
                'expanded' => true
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Valider ma commande',
                'attr' => [
                    'class' => 'btn btn-success btn-block'
                ]
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'user' => array()
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use DateTime;
use App\Classe\Cart;
use App\Entity\Order;
use App\Form\OrderType;
use App\Entity\OrderDetails;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class OrderController extends AbstractController
{

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/commande', name: 'order')]
    public function index(Cart $cart): Response
    {
        // Si l'utilisateur n'a pas d'adresses ALORS
        if (!$this->getUser()->getAddresses()->getValues()) {
            // On le redirige vers la page d'ajout d'adresse
            return $this->redirectToRoute('account_address_add');
        }

        $form = $this->createForm(OrderType::class, null, [
            'user' => $this->getUser()
        ]);




        return $this->render('order/index.html.twig', [
            'form' => $form->createView(),
            'cart' => $cart->getFull()
        ]);
        // var_dump($cart);
    }

    #[Route('/commande/recapitulatif', name: 'order_recap')]
    public function add(Cart $cart, Request $request): Response
    {
        $form = $this->createForm(OrderType::class, null, [
            'user' => $this->getUser()
        ]);

        // Ecoute la requête
        $form->handleRequest($request);

        // SI le formulaire est soumis ET le formulaire est valide ALORS
        if ($form->isSubmitted() && $form->isValid()) {
            $order = new Order();
            $date = new DateTime();

            // Récupère le champ du formulaire
            $carriers = $form->get('carriers')->getData();
            $delivery = $form->get('addresses')->getData();

            $delivery_content = $delivery->getFirstname().' '.$delivery->getLastname();
            $delivery_content .= '<br>'.$delivery->getPhone();

            if ($delivery->getCompany()) {
                $delivery_content .= '<br>'.$delivery->getCompany();
            }

            $delivery_content .= '<br>'.$delivery->getAddress();
            $delivery_content .= '<br>'.$delivery->getPostal().' '.$delivery->getCity();
            $delivery_content .= '<br>'.$delivery->getCountry();

            // dd($delivery_content);

            // dd($carriers);


            $reference = $date->format('dmY').'-'.uniqid();
            $order->setReference($reference);

            // Enregistrer ma commande Order()
            $order->setUser($this->getUser());

            $order->setCreatedAt($date);

            // Définit le nom de carriers
            $order->setCarrierName($carriers->getName());

            // Définit le prix de carriers
            $order->setCarrierPrice($carriers->getPrice());

            $order->setDelivery($delivery_content);

            $order->setIsPaid(0);

            // Fige la data
            $this->entityManager->persist($order);

            // Pour chaque produit que j'ai dans mon panier
           

            foreach($cart->getFull() as $product){

                // Enregistrer mes produits OrderDetails()
                $orderDetails = new OrderDetails();
                $orderDetails->setMyOrder($order);
                $orderDetails->setProduct($product['product']->getName());
                $orderDetails->setQuantity($product['quantity']);
                $orderDetails->setPrice($product['product']->getPrice());
                $orderDetails->setTotal($product['product']->getPrice() * $product['quantity']);
               
                // Fige la data
                $this->entityManager->persist($orderDetails);


            }

                $this->entityManager->flush();

                // STRIP fait le lien entre la banque et notre site :D

    
                    
                    // dump($checkout_session->id);
                    // dd($checkout_session);
           
            return $this->render('order/add.html.twig', [
                'cart' => $cart->getFull(),
                'carrier' => $carriers,
                'delivery' => $delivery_content,
                'reference' => $order->getReference()
            ]);
            
        }

        return $this->redirectToRoute('cart');
            
    }
        
}

templates/order/add.html.twig
{% extends 'base.html.twig' %}
{% block javascript %}
<script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block title %}Paiement de  ma commande - WestCoast{% endblock %}

{% block content %}
    <h2>Mon récapitulatif</h2>
    <p>Vérifiez vos informations avant de payer votre commande.</p>
    <hr>
    <div class="row">
        <div class="col-md-6">
          <strong>Mon adresse de livraison</strong><br>
          <div class="form-check mt-4">
            {{delivery|raw}}
          </div>

          <hr>

          <strong>Mon transporteur</strong><br>
          <div class="form-check">
            {{carrier.name}}<br>
            {{carrier.description}}<br>
            {{carrier.price|number_format(2, ',')}} €
          </div>
          
        </div>
        <div class="col-md-6">
            <div class="text-center">
                <b>Ma commande</b><br>
            </div>
            <div class="order-summary">
                {% set total = null %}  

                {% for key,product in cart %}
                <div class="row {% if key > 0 %}mt-2{% endif %}">
                    <div class="col-2">
                        <img src="/uploads/{{product.product.illustration}}" alt="{{product.product.name}}" height="75px">
                    </div>
                    <div class="col-8 my-auto">
                        {{product.product.name}}<br>
                        <small>
                          {{product.product.subtitle}}
                          <br>
                          x {{product.quantity}}
                        </small>
                    </div>
                    <div class="col-2 my-auto">
                      {{ ((product.product.price * product.quantity) / 100)|number_format(2, ',')}}
                    </div>
                </div>
                {% set total = total +  (product.product.price * product.quantity)%}
                {% endfor %}
            </div>

            <hr>
            <strong>Sous-total : </strong> {{(total / 100)|number_format(2, ',')}} € <br>
            <strong>Livraison : </strong> {{(carrier.price)|number_format(2, ',')}} €
            <hr>
            <strong>Total : </strong> {{((total / 100) + carrier.price)|number_format(2, ',')}} €

            <a href="{{ path('stripe_create_session', {'reference': reference}) }}"class="btn btn-success btn-block mt-3">Payer | {{ ((total / 100) + carrier.price / 100) | number_format(2, ',', '.') }}€</a>
        </div>
    </div>  
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Valider ma commande - WestCoast Sneakers{% endblock %}

{% block content %}
    <div class="container">
    <h2>Je passe ma commande</h2>
    <p>Choisissez vos préférences avant de passer votre commande sur La Boutique Française</p><div>
    
    <hr>
    <div class="row">
        <div class="col-md-6">
            <b>Choisir mon adresse de livraison</b><br>
            {% set formHtml %}
            {{form_start(form, {action:path('order_recap')})}}
            {{form_end(form)}}
            {% endset %}
            {{formHtml|replace({'[br]':'<br>'})|raw}}
        </div>
        <div class="col-md-6">
        <div class="text-center">
                <b>Récap de ma commande</b><br>
                <p>Retrouvez le récapitulatif de vos produits</p>
            </div>
        <div class="order-summary">
                {% for key,product in cart %}
                    <div class="row {% if key > 0 %}mt-2{% endif %}">
                        <div class="col-2">
                            <img src="/uploads/{{product.product.illustration}}" alt="{{product.product.name}}" height="75px">
                        </div>
                        <div class="col-8 my-auto">
                            {{product.product.name}}<br>
                            <small>{{product.product.subtitle}}</small>
                        </div>
                        <div class="col-2 my-auto">
                            x
                            {{product.quantity}}
                        </div>
                    </div>
                {% endfor %}
            </div>
         <b>Bouton pour payer</b> 
        </div>
    </div>

    <hr>
    </div>

{% endblock %}